### ISSUE TITLE
Error downloading nightly prereleases in 0.5.1

### ISSUE THREAD

**Issue by erikvold** [mozilla-b2g/mozilla-download#15]
I suspect since we reverted to a previous version of mozilla.-get-url and no longer use this patch https://github.com/mozilla-b2g/mozilla-get-url/commit/0ea5d83aaf6a1378b28583c44a0698de05e12ba1 we now regress on nightly prerelease downloads, and the [mozilla/addon-sdk](https://github.com/mozilla/addon-sdk/) travis test suite now breaks due to this regression.

**Comment by erikvold** [comment]
ah it looks like the issue is actually due to new "sdk" builds being made available, which are now downloaded by mistake, and since they are much larger unpacking them causes a the max buffer error that was in the example I provided above.

**Comment by wilsonpage** [comment]
I'm also running into the `.stdout maxBuffer exceeded` error in all my Travis runs. @lightsofapollo can you shed any light on this?

**Comment by wilsonpage** [comment]
[Example](https://travis-ci.org/gaia-components/gaia-header/#L315)

**Comment by lightsofapollo-taskcluster** [comment]
@wilsonpage @gaye 

Hey Wilson can you try again with 1.0.3 ? (email / bugzilla is best way to reach me sorry for delay here @erikvold )
